- src/components/common/Dropdown.tsx
드롭다운 컴포넌트 퍼블리싱
드롭다운 컴포넌트 퍼블리싱
사용예시
- Close #SCRUM-129
> design: 드롭다운 컴포넌트 퍼블리싱 issue: SCRUM-129

- .storybook/main.ts
- .storybook/preview.ts
- src/app/project/[id]/page.tsx
- src/components/project/Card.tsx
- src/components/project/detail/Member.tsx
- src/components/project/detail/Stack.tsx
- src/stories/project/Member.stories.tsx
- src/stories/project/Stack.stories.tsx
- yarn.lock
프로젝트 상세 페이지 Member, Stack 컴포넌트 storybook 생성
<br><br>
- Close #이슈번호
<br><br>
> feat: 프로젝트 상세 페이지 Member, Stack 컴포넌트 storybook 생성

- src/components/common/Dropdown.tsx
- src/components/common/InputField.tsx
- src/components/signup/ExperienceSection.tsx
- src/components/signup/PositionSelect.tsx
- src/stories/common/Dropdown.stories.tsx
- src/stories/common/InputField.stories.tsx
- src/stories/signup/ExperienceSection.stories.tsx
- src/stories/signup/PositionSelect.stories.tsx
회원가입 관련 컴포넌트 스토리북 생성
인풋, 드롭다운, 경력 질문, 포지션 선택 컴포넌트 스토리북 생성
- Close #SCRUM-150
<br><br>
> feat: 회원가입 관련 컴포넌트 스토리북 생성

- src/app/detail/page.tsx
- src/components/common/SearchBar.tsx
- src/components/profile/ProfileBox.tsx
- src/stories/components/ProfileBox.stories.tsx
- src/stories/components/TapBar.stories.tsx
탭바, 프로필박스 스토리북
<br><br>
6009c">
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> test: 탭바, 프로필박스 스토리북

- src/app/changepassword/page.tsx
- src/app/detail/page.tsx
- src/app/login/page.tsx
- src/app/project/add/project/@modal/(.)addMember/page.tsx
- src/app/project/add/project/addMember/page.tsx
- src/app/project/add/study/@modal/(.)addMember/page.tsx
- src/app/project/detail/project/[id]/page.tsx
- src/app/resume/layout.tsx
- src/app/search/page.tsx
- src/components/calender/Calendar.tsx
- src/components/project/add/AddBtn.tsx
- src/components/project/add/AddMember.tsx
- src/components/project/add/AddRecruit.tsx
- src/components/project/add/project/AddResults.tsx
- src/components/project/add/study/AddGoal.tsx
- src/components/project/detail/Member.tsx
- src/components/project/modal/ProjectModal.tsx
- src/components/project/modal/StudyModal.tsx
- src/components/resume/OtherResume.tsx
- src/components/resume/ResumeFolder.tsx
- src/components/search/CategoryTab.tsx
- src/stories/Page.tsx
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> feat : 빌드 에러 수정

- package.json
- src/app/layout.tsx
- src/utils/get-query-client.ts
- src/utils/provider.tsx
- yarn.lock
tanstack-query 초기 설정 완료
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> set: tanstack-query 초기 설정 완료

- src/app/mypage/page.tsx
- src/app/signup/page.tsx
- src/components/common/NevBar.tsx
- src/components/mypage/Carousel.tsx
- src/components/mypage/Home.tsx
- src/components/mypage/MyExperienceSection.tsx
- src/components/mypage/Profile.tsx
- src/components/signup/ExperienceItem.tsx
- src/components/signup/ExperienceSection.tsx
- src/store/authStore.ts
내 정보 수정, 경력 삭제
<br><br>
- 내 정보 수정에서 경력 수정 가능하게 변경
- 삭제 api 연동
- 경력 컴포넌트 오류 수정
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> fix: 내 정보 수정, 경력 삭제

- src/app/profile/@profiletList.tsx
- src/app/profile/api/getProfileList.ts
- 프로필 페이지 무한 스크롤 구현
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> feat :프로필 페이지 무한스크롤 구현

- package.json
- src/app/blog/page.tsx
- src/app/project/page.tsx
- src/app/resume/api/getBestResume.ts
- src/app/resume/page.tsx
- src/app/session/page.tsx
- src/app/signup/page.tsx
- src/components/project/SkeletonProjectCard.tsx
- src/components/resume/BestResume.tsx
- yarn.lock
<br><br>
회원가입 로딩 로티 
블로그 로딩, 데이터 없는 경우 처리
세션, 이력서 로그인 안한 경우 모달 + 데이터 없게 처리
프로젝트 스켈레톤 구현
<br><br>
<br><br>
- Close #SCRUM-249
<br><br>
> feat: 로딩 스켈레톤 적용

- src/api/project/common.ts
- src/app/profile/page.tsx
- src/app/project/page.tsx
- src/components/project/detail/study/Results.tsx
- src/components/project/modal/study/ApplicantModal.tsx
- src/components/session/FilterBtn.tsx
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> feat: 프로젝트 페이지 필터링

- src/app/resume/page.tsx
- src/app/search/final/page.tsx
이력서 포지션 필터링 수정 및 통합검색 페이지 로티 출력
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> fix: 이력서 포지션 필터링 수정 및 통합검색 페이지 로티 출력

- next.config.mjs
- src/app/signup/page.tsx
fix: 회원가입 깃허브 링크 필수로 수정
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> fix: 회원가입 깃허브 링크 필수로 수정

- src/app/signup/page.tsx
- src/components/common/TapBar.tsx
- src/components/mypage/Bookmark.tsx
- src/components/mypage/Carousel.tsx
- src/components/mypage/Likes.tsx
- src/components/project/add/AddMember.tsx
- src/components/project/add/study/AddMember.tsx
- src/components/project/detail/Member.tsx
- src/components/project/detail/Results.tsx
- src/components/project/detail/study/Applicants.tsx
- src/components/project/detail/study/Member.tsx
- src/components/project/detail/study/Results.tsx
- src/components/project/modal/ApplicantModal.tsx
- src/components/project/modal/BigMemberBox.tsx
- src/components/project/modal/ProjectModal.tsx
- src/components/project/modal/study/ApplicantModal.tsx
- src/components/project/modal/study/SmallMemberBox.tsx
- src/components/project/modal/study/StudyModal.tsx
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> fix: 회원가입 오류 수정 및 마이페이지 empty 처리

- src/components/project/ProjectCard.tsx
- src/components/project/StudyCard.tsx
- src/components/project/add/AddRecruit.tsx
- src/components/project/add/study/AddRecruit.tsx
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> fix: 프로젝트, 스터디 등록 오류 수정

- next.config.mjs
스테이징 프리뷰 업데이트
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> feat: env var for next config (#70) SCRUM-304

- src/api/auth/auth.ts
- src/app/changepassword/page.tsx
- src/app/mypage/leave/page.tsx
- src/app/profile/@profiletList.tsx
- src/app/profile/api/getProfileList.ts
- src/app/profile/page.tsx
- src/app/profile/query/useGetProfileQuery.ts
- src/app/signup/page.tsx
- src/components/common/EmailVerification.tsx
- src/components/common/ExperienceBtn.tsx
- src/components/common/NavBar.tsx
- src/components/mypage/Profile.tsx
- src/components/signup/ExperienceItem.tsx
- src/components/signup/ExperienceSection.tsx
- src/constants/signupInfo.ts
- src/hooks/auth/useLogin.ts
- src/hooks/auth/useSignupHandler.ts
- src/hooks/mypage/useFetchProfile.ts
- src/store/authStore.ts
- src/types/mypage/mypage.types.ts
- src/types/queryParams.ts
- src/types/signup/signup.type.ts
유저 스프링 서버 연동 수정
- 경력 설명란 추가
- 외부인 회원가입 연동
- 모든 프로필 조회 커서 기반 페이징 적용
- 권한별 NavBar 접근 제한
- Close FRONTEND-321
> fix: 유저 스프링 서버 연동 수정

- src/app/resume/@resumeList.tsx
- src/app/resume/api/getResumeList.ts
- src/app/resume/page.tsx
- src/app/resume/query/useGetResumeQuery.ts
- src/types/queryParams.ts
이력서 목록 조회 최신순/조회순 안되는 이슈 해결
<br><br>
<br><br>
<br><br>
- Close TECHEER-12
<br><br>
> fix: 이력서 목록 조회 최신순/조회순 안되는 이슈 해결

- src/api/session/session.ts
- src/components/session/SessionList.tsx
- src/hooks/session/useSessionsQuery.ts
세션 무한스크롤 재연동
세션 무한스크롤 재연동
- Close TECHEER-16
> feat: 세션 무한스크롤 재연동

- src/components/calender/AddCalendarModal.tsx
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> style: 취업공고 -> 지원 공고로 변경

- src/api/bootcamp/createBootcamp.ts
- src/api/bootcamp/getBootcampList.ts
- src/api/bootcamp/getBootcampMembers.ts
- src/api/bootcamp/toogleBootcampParticipation.ts
- src/api/bootcamp/updateBootcamp.ts
- src/app/bootcamp/page.tsx
- src/components/bootcamp/AddMemberModal.tsx
- src/components/bootcamp/BootcampModal.tsx
- src/components/bootcamp/BootcampModal/ModalHeader.tsx
- src/components/bootcamp/BootcampModal/ProjectTeam.tsx
- src/components/bootcamp/RegistModal.tsx
- src/components/bootcamp/RegistModal/ProjectExplain.tsx
- src/components/bootcamp/RegistModal/ProjectImage.tsx
- src/components/bootcamp/RegistModal/ProjectLinkInput.tsx
- src/components/bootcamp/RegistModal/ProjectMembers.tsx
- src/components/bootcamp/RegistModal/ProjectTeamName.tsx
- src/components/bootcamp/RegistModal/ProjectTitleInput.tsx
- src/components/bootcamp/main/BootcampHeader.tsx
- src/components/bootcamp/main/ProjectItem.tsx
- src/components/bootcamp/main/ProjectList.tsx
- src/components/bootcamp/main/ProjectListSkeleton.tsx
- src/hooks/bootcamp/useGetBootcampList.ts
- src/types/bootcamp/bootcamp.ts
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> [Feat] 테커로그 기능 구현
